Repository KMU-WINK/kmu-wink-official, pull requests merged in 2020-10, with the labels that each got.

#14 팀 소개 README.md
  README.md
  WORKFLOW.md
Labels: documentation

#12 Comments branch: 댓글 CRUD 기능 구현
  board/urls.py
  board/views.py
  static/css/board.css
  templates/board_skin/document.html
Labels: 기능 개선, 새로운 기능

#13 게시물 글쓰기 CKeditor 기능 추가
  board/models.py
  templates/board_skin/write.html
  wink_official/urls.py
Labels: 기능 개선, 새로운 기능

#15 글쓰기 수정기능 추가
  .gitignore
  board/urls.py
  board/views.py
  templates/board_skin/document.html
Labels: 기능 개선, 새로운 기능

#20 글 작성 후 html tag 그대로 출력하는 이슈 해결
  .gitignore
  README.md
  WORKFLOW.md
  board/urls.py
  board/views.py
  static/css/board.css
  templates/board_skin/document.html
Labels: bug
